name: Feature Request
description: Suggest a new feature or enhancement
labels: ['enhancement']
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide details to help us understand your request.
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you want to add.
      placeholder: 'I would like to add support for dark mode toggling in the UI.'
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain the problem this feature solves or how it improves the project.
      placeholder: 'This feature would allow users to switch between light and dark themes for better accessibility.'
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Suggest how this feature could be implemented, if you have ideas.
      placeholder: 'Add a theme toggle button in the header that updates TailwindCSS classes.'
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: 'Manually adding dark mode classes to components, but this is less user-friendly.'
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, such as mockups or references to similar features.
      placeholder: 'Inspired by Next.js documentation dark mode implementation.'
    validations:
      required: false
