/* tslint:disable */
/* eslint-disable */
/**
 * E-commerce API
 * API for managing products, orders, and users in an e-commerce platform
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface Brand
 */
export interface Brand {
    /**
     * 
     * @type {number}
     * @memberof Brand
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof Brand
     */
    'logo'?: string;
}
/**
 * 
 * @export
 * @interface Category
 */
export interface Category {
    /**
     * 
     * @type {number}
     * @memberof Category
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Category
     */
    'slug'?: string;
}
/**
 * 
 * @export
 * @interface CreateOrderRequest
 */
export interface CreateOrderRequest {
    /**
     * 
     * @type {CreateOrderRequestOrders}
     * @memberof CreateOrderRequest
     */
    'orders'?: CreateOrderRequestOrders;
}
/**
 * 
 * @export
 * @interface CreateOrderRequestOrders
 */
export interface CreateOrderRequestOrders {
    /**
     * 
     * @type {Array<CreateOrderRequestOrdersOrderItemsInner>}
     * @memberof CreateOrderRequestOrders
     */
    'order_items'?: Array<CreateOrderRequestOrdersOrderItemsInner>;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'payment_method'?: CreateOrderRequestOrdersPaymentMethodEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'order_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'delivery_type'?: CreateOrderRequestOrdersDeliveryTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'delivery_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'store_location'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'coupon_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'guest_email'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'guest_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrderRequestOrders
     */
    'guest_name'?: string;
}

export const CreateOrderRequestOrdersPaymentMethodEnum = {
    CreditCard: 'credit_card',
    Paypal: 'paypal',
    BankTransfer: 'bank_transfer',
    Cod: 'cod'
} as const;

export type CreateOrderRequestOrdersPaymentMethodEnum = typeof CreateOrderRequestOrdersPaymentMethodEnum[keyof typeof CreateOrderRequestOrdersPaymentMethodEnum];
export const CreateOrderRequestOrdersDeliveryTypeEnum = {
    Home: 'home',
    StorePickup: 'store_pickup'
} as const;

export type CreateOrderRequestOrdersDeliveryTypeEnum = typeof CreateOrderRequestOrdersDeliveryTypeEnum[keyof typeof CreateOrderRequestOrdersDeliveryTypeEnum];

/**
 * 
 * @export
 * @interface CreateOrderRequestOrdersOrderItemsInner
 */
export interface CreateOrderRequestOrdersOrderItemsInner {
    /**
     * 
     * @type {number}
     * @memberof CreateOrderRequestOrdersOrderItemsInner
     */
    'product_id': number;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderRequestOrdersOrderItemsInner
     */
    'variant_id'?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateOrderRequestOrdersOrderItemsInner
     */
    'quantity': number;
}
/**
 * 
 * @export
 * @interface ListOrders200Response
 */
export interface ListOrders200Response {
    /**
     * 
     * @type {Array<Order>}
     * @memberof ListOrders200Response
     */
    'orders'?: Array<Order>;
    /**
     * 
     * @type {ListProducts200ResponseMeta}
     * @memberof ListOrders200Response
     */
    'meta'?: ListProducts200ResponseMeta;
}
/**
 * 
 * @export
 * @interface ListProducts200Response
 */
export interface ListProducts200Response {
    /**
     * 
     * @type {Array<Product>}
     * @memberof ListProducts200Response
     */
    'products'?: Array<Product>;
    /**
     * 
     * @type {ListProducts200ResponseMeta}
     * @memberof ListProducts200Response
     */
    'meta'?: ListProducts200ResponseMeta;
}
/**
 * 
 * @export
 * @interface ListProducts200ResponseMeta
 */
export interface ListProducts200ResponseMeta {
    /**
     * 
     * @type {number}
     * @memberof ListProducts200ResponseMeta
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListProducts200ResponseMeta
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof ListProducts200ResponseMeta
     */
    'per_page'?: number;
}
/**
 * 
 * @export
 * @interface ListStores200Response
 */
export interface ListStores200Response {
    /**
     * 
     * @type {Array<Store>}
     * @memberof ListStores200Response
     */
    'stores'?: Array<Store>;
}
/**
 * 
 * @export
 * @interface Listbrands200Response
 */
export interface Listbrands200Response {
    /**
     * 
     * @type {Array<Brand>}
     * @memberof Listbrands200Response
     */
    'stores'?: Array<Brand>;
}
/**
 * 
 * @export
 * @interface Listcategory200Response
 */
export interface Listcategory200Response {
    /**
     * 
     * @type {Array<Category>}
     * @memberof Listcategory200Response
     */
    'stores'?: Array<Category>;
}
/**
 * 
 * @export
 * @interface Order
 */
export interface Order {
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'order_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'subtotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'discount_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'shipping_fee'?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'tax_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof Order
     */
    'total_amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'payment_method'?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'payment_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'delivery_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Order
     */
    'created_at'?: string;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof Order
     */
    'order_items'?: Array<OrderItem>;
}
/**
 * 
 * @export
 * @interface OrderDetail
 */
export interface OrderDetail {
    /**
     * 
     * @type {number}
     * @memberof OrderDetail
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'order_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'status'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderDetail
     */
    'subtotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDetail
     */
    'discount_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDetail
     */
    'shipping_fee'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDetail
     */
    'tax_amount'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDetail
     */
    'total_amount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'payment_method'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'payment_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'delivery_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'delivery_address'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'store_location'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'notes'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'coupon_code'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderDetail
     */
    'coupon_discount'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'guest_email'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'guest_phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'guest_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderDetail
     */
    'created_at'?: string;
    /**
     * 
     * @type {Array<OrderItem>}
     * @memberof OrderDetail
     */
    'order_items'?: Array<OrderItem>;
}
/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'id'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'product_id'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    'product_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    'product_sku'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderItem
     */
    'product_image'?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'unit_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderItem
     */
    'total_price'?: number;
    /**
     * 
     * @type {object}
     * @memberof OrderItem
     */
    'variant_info'?: object;
}
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'id'?: number;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    'name'?: string;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    'slug'?: string;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'price'?: number;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'original_price'?: string;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'discount_percent'?: number;
    /**
     *
     * @type {boolean}
     * @memberof Product
     */
    'is_active'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof Product
     */
    'is_featured'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof Product
     */
    'is_new'?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof Product
     */
    'is_hot'?: boolean;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'stock_quantity'?: number;
    /**
     * Payment Options - Added manually
     * @type {boolean}
     * @memberof Product
     */
    'full_payment_transfer'?: boolean;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'full_payment_discount_percentage'?: number;
    /**
     *
     * @type {boolean}
     * @memberof Product
     */
    'partial_advance_payment'?: boolean;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'advance_payment_percentage'?: number;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'advance_payment_discount_percentage'?: number;
    /**
     *
     * @type {Array<ProductImage>}
     * @memberof Product
     */
    'images'?: Array<ProductImage>;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    'short_description'?: string;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    'description'?: string;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    'meta_title'?: string;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    'meta_description'?: string;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'view_count'?: number;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'preorder_quantity'?: number;
    /**
     *
     * @type {string}
     * @memberof Product
     */
    'preorder_end_date'?: string;
    /**
     *
     * @type {number}
     * @memberof Product
     */
    'warranty_period'?: number;
    /**
     *
     * @type {boolean}
     * @memberof Product
     */
    'is_preorder'?: boolean;
}
/**
 * 
 * @export
 * @interface ProductDetail
 */
export interface ProductDetail {
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'slug'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'sku'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'short_description'?: string;
    /**
     * 
     * @type {Brand}
     * @memberof ProductDetail
     */
    'brand'?: Brand;
    /**
     * 
     * @type {Category}
     * @memberof ProductDetail
     */
    'category'?: Category;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'price'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'original_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'discount_percent'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'cost_price'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'weight'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'dimensions'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'stock_quantity'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'min_stock_alert'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDetail
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDetail
     */
    'is_featured'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDetail
     */
    'is_new'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDetail
     */
    'is_hot'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ProductDetail
     */
    'is_preorder'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'preorder_quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'preorder_end_date'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'warranty_period'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'meta_title'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductDetail
     */
    'meta_description'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductDetail
     */
    'view_count'?: number;
    /**
     * 
     * @type {Array<ProductImage>}
     * @memberof ProductDetail
     */
    'images'?: Array<ProductImage>;
    /**
     * 
     * @type {Array<ProductVariant>}
     * @memberof ProductDetail
     */
    'variants'?: Array<ProductVariant>;
    /**
     *
     * @type {Array<ProductSpecification>}
     * @memberof ProductDetail
     */
    'specifications'?: Array<ProductSpecification>;
    /**
     * Payment Options - Added manually
     * @type {boolean}
     * @memberof ProductDetail
     */
    'full_payment_transfer'?: boolean;
    /**
     *
     * @type {number}
     * @memberof ProductDetail
     */
    'full_payment_discount_percentage'?: number;
    /**
     *
     * @type {boolean}
     * @memberof ProductDetail
     */
    'partial_advance_payment'?: boolean;
    /**
     *
     * @type {number}
     * @memberof ProductDetail
     */
    'advance_payment_percentage'?: number;
    /**
     *
     * @type {number}
     * @memberof ProductDetail
     */
    'advance_payment_discount_percentage'?: number;
}
/**
 * 
 * @export
 * @interface ProductImage
 */
export interface ProductImage {
    /**
     * 
     * @type {number}
     * @memberof ProductImage
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductImage
     */
    'image_url'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductImage
     */
    'alt_text'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductImage
     */
    'sort_order'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ProductImage
     */
    'is_primary'?: boolean;
}
/**
 * 
 * @export
 * @interface ProductSpecification
 */
export interface ProductSpecification {
    /**
     * 
     * @type {number}
     * @memberof ProductSpecification
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecification
     */
    'spec_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductSpecification
     */
    'spec_value'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductSpecification
     */
    'sort_order'?: number;
}
/**
 * 
 * @export
 * @interface ProductVariant
 */
export interface ProductVariant {
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    'variant_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    'variant_value'?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    'price_adjustment'?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductVariant
     */
    'stock_quantity'?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductVariant
     */
    'sku'?: string;
}
/**
 * 
 * @export
 * @interface Store
 */
export interface Store {
    /**
     * Unique identifier for the store.
     * @type {number}
     * @memberof Store
     */
    'id'?: number;
    /**
     * Name of the store.
     * @type {string}
     * @memberof Store
     */
    'name'?: string;
    /**
     * Full address of the store.
     * @type {string}
     * @memberof Store
     */
    'address'?: string;
    /**
     * Contact phone number of the store.
     * @type {string}
     * @memberof Store
     */
    'phone'?: string | null;
    /**
     * Contact email of the store.
     * @type {string}
     * @memberof Store
     */
    'email'?: string | null;
    /**
     * City where the store is located.
     * @type {string}
     * @memberof Store
     */
    'city'?: string;
    /**
     * Indicates if the store is active.
     * @type {boolean}
     * @memberof Store
     */
    'is_active'?: boolean;
    /**
     * JSON object containing the store\'s opening hours.
     * @type {object}
     * @memberof Store
     */
    'opening_hours'?: object | null;
    /**
     * Timestamp when the store was created.
     * @type {string}
     * @memberof Store
     */
    'created_at'?: string;
    /**
     * Timestamp when the store was last updated.
     * @type {string}
     * @memberof Store
     */
    'updated_at'?: string;
}
/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {number}
     * @memberof User
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatar'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'date_of_birth'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'gender'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'is_active'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof User
     */
    'is_verified'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'email_verified_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'phone_verified_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'last_login_at'?: string;
    /**
     * 
     * @type {Array<UserAddress>}
     * @memberof User
     */
    'addresses'?: Array<UserAddress>;
}
/**
 * 
 * @export
 * @interface UserAddress
 */
export interface UserAddress {
    /**
     * 
     * @type {number}
     * @memberof UserAddress
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'full_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'address_line1'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'address_line2'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'postal_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddress
     */
    'country'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserAddress
     */
    'is_default'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserAddress
     */
    'is_active'?: boolean;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new order
         * @param {CreateOrderRequest} createOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder: async (createOrderRequest: CreateOrderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createOrderRequest' is not null or undefined
            assertParamExists('createOrder', 'createOrderRequest', createOrderRequest)
            const localVarPath = `/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createOrderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get order details
         * @param {string} id Order ID or order number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrder: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getOrder', 'id', id)
            const localVarPath = `/orders/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get product details
         * @param {string} id Product ID or slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProduct: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getProduct', 'id', id)
            const localVarPath = `/products/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get authenticated user details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all orders for the authenticated user
         * @param {number} [page] Page number for pagination
         * @param {number} [perPage] Number of orders per page
         * @param {ListOrdersStatusEnum} [status] Filter by order status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOrders: async (page?: number, perPage?: number, status?: ListOrdersStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/orders`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all products
         * @param {number} [page] Page number for pagination
         * @param {number} [perPage] Number of products per page
         * @param {number} [categoryId] Filter by category ID
         * @param {number} [brandId] Filter by brand ID
         * @param {boolean} [isActive] Filter by active status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProducts: async (page?: number, perPage?: number, categoryId?: number, brandId?: number, isActive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (perPage !== undefined) {
                localVarQueryParameter['per_page'] = perPage;
            }

            if (categoryId !== undefined) {
                localVarQueryParameter['category_id'] = categoryId;
            }

            if (brandId !== undefined) {
                localVarQueryParameter['brand_id'] = brandId;
            }

            if (isActive !== undefined) {
                localVarQueryParameter['is_active'] = isActive;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all stores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStores: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stores`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all brands
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listbrands: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/brands`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List all Cagegory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listcategory: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new order
         * @param {CreateOrderRequest} createOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrder(createOrderRequest: CreateOrderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Order>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrder(createOrderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get order details
         * @param {string} id Order ID or order number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrder(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrderDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrder(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getOrder']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get product details
         * @param {string} id Product ID or slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProduct(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductDetail>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProduct(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getProduct']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get authenticated user details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<User>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all orders for the authenticated user
         * @param {number} [page] Page number for pagination
         * @param {number} [perPage] Number of orders per page
         * @param {ListOrdersStatusEnum} [status] Filter by order status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOrders(page?: number, perPage?: number, status?: ListOrdersStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListOrders200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listOrders(page, perPage, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listOrders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all products
         * @param {number} [page] Page number for pagination
         * @param {number} [perPage] Number of products per page
         * @param {number} [categoryId] Filter by category ID
         * @param {number} [brandId] Filter by brand ID
         * @param {boolean} [isActive] Filter by active status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listProducts(page?: number, perPage?: number, categoryId?: number, brandId?: number, isActive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListProducts200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listProducts(page, perPage, categoryId, brandId, isActive, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listProducts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all stores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listStores(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListStores200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listStores(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listStores']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all brands
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listbrands(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Listbrands200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listbrands(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listbrands']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List all Cagegory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listcategory(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Listcategory200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listcategory(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listcategory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new order
         * @param {CreateOrderRequest} createOrderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrder(createOrderRequest: CreateOrderRequest, options?: RawAxiosRequestConfig): AxiosPromise<Order> {
            return localVarFp.createOrder(createOrderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get order details
         * @param {string} id Order ID or order number
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrder(id: string, options?: RawAxiosRequestConfig): AxiosPromise<OrderDetail> {
            return localVarFp.getOrder(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get product details
         * @param {string} id Product ID or slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProduct(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ProductDetail> {
            return localVarFp.getProduct(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get authenticated user details
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(options?: RawAxiosRequestConfig): AxiosPromise<User> {
            return localVarFp.getUser(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all orders for the authenticated user
         * @param {number} [page] Page number for pagination
         * @param {number} [perPage] Number of orders per page
         * @param {ListOrdersStatusEnum} [status] Filter by order status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOrders(page?: number, perPage?: number, status?: ListOrdersStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<ListOrders200Response> {
            return localVarFp.listOrders(page, perPage, status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all products
         * @param {number} [page] Page number for pagination
         * @param {number} [perPage] Number of products per page
         * @param {number} [categoryId] Filter by category ID
         * @param {number} [brandId] Filter by brand ID
         * @param {boolean} [isActive] Filter by active status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listProducts(page?: number, perPage?: number, categoryId?: number, brandId?: number, isActive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ListProducts200Response> {
            return localVarFp.listProducts(page, perPage, categoryId, brandId, isActive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all stores
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStores(options?: RawAxiosRequestConfig): AxiosPromise<ListStores200Response> {
            return localVarFp.listStores(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all brands
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listbrands(options?: RawAxiosRequestConfig): AxiosPromise<Listbrands200Response> {
            return localVarFp.listbrands(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List all Cagegory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listcategory(options?: RawAxiosRequestConfig): AxiosPromise<Listcategory200Response> {
            return localVarFp.listcategory(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new order
     * @param {CreateOrderRequest} createOrderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createOrder(createOrderRequest: CreateOrderRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createOrder(createOrderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get order details
     * @param {string} id Order ID or order number
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getOrder(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getOrder(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get product details
     * @param {string} id Product ID or slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getProduct(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getProduct(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get authenticated user details
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getUser(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getUser(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all orders for the authenticated user
     * @param {number} [page] Page number for pagination
     * @param {number} [perPage] Number of orders per page
     * @param {ListOrdersStatusEnum} [status] Filter by order status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listOrders(page?: number, perPage?: number, status?: ListOrdersStatusEnum, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listOrders(page, perPage, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all products
     * @param {number} [page] Page number for pagination
     * @param {number} [perPage] Number of products per page
     * @param {number} [categoryId] Filter by category ID
     * @param {number} [brandId] Filter by brand ID
     * @param {boolean} [isActive] Filter by active status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listProducts(page?: number, perPage?: number, categoryId?: number, brandId?: number, isActive?: boolean, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listProducts(page, perPage, categoryId, brandId, isActive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all stores
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listStores(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listStores(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all brands
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listbrands(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listbrands(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List all Cagegory
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public listcategory(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listcategory(options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ListOrdersStatusEnum = {
    Pending: 'pending',
    Processing: 'processing',
    Shipped: 'shipped',
    Delivered: 'delivered',
    Cancelled: 'cancelled'
} as const;
export type ListOrdersStatusEnum = typeof ListOrdersStatusEnum[keyof typeof ListOrdersStatusEnum];


